
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production \
    MONGODB_URI=mongodb+srv://icelink39:1234@cluster.21g6q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster \
    PORT=8088 \
    JWT_SECRET=fkwru38ohdfw8r3o18hr2n23on3xr8d7x2di2q37e2djb1200ws \
    STRIPE_SECRET_KEY=sk_test_51RenlXPGV9ff9hRnQbBVhKpmIy79iMS0yMARV4zplcqSxJ5Nw9y5mWeZXPhEH2u5VEZzdBIwRLNNrmUY8NgnRE8Q00OJOt4bqN


EXPOSE 8088

CMD ["node", "dist/main.js"]
